language: node_js
branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.npm'

audit:
  script:
    - npm audit
  allow_failures: true

before_install:
  - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
install:
  - npm install

deploy:
  skip_cleanup: true
  provider: npm
  email: ${NPM_EMAIL}
  api_key: ${API_TOKEN}
