language: node_js
cache:
  directories:
    - '$HOME/.npm'
git.checkout:
  - git clone --depth=50 https://pedro-gomes-92:$GIT_TOKEN@github.com/dots.git
install:
  - npm install

jobs:
  include:
    - stage: test
      name: 'Test solution'
      script:
        - npm audit
        - npm test

    - stage: version
      if: branch = master and type = pull_request
      name: 'Bump new NPM version'
      install: skip
      before_script:
        - npm run git:ci --username $GIT_NAME --email $GIT_EMAIL --token $GIT_TOKEN
      script:
        - npm run version:branch $TRAVIS_PULL_REQUEST_BRANCH

    - stage: deploy
      if: branch = master and type = pull_request
      name: 'Deploy package'
      before_deploy:
        - npm run build:prod
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        cleanup: true
