language: node_js
cache:
  directories:
    - '$HOME/.npm'
before_install:
  - echo -e "machine github.com\n  login $GIT_TOKEN" > ~/.netrc
  - git lfs pull
  - git config --global user.name="$GIT_NAME"
  - git config --global user.email="$GIT_EMAIL"
install:
  - npm install

jobs:
  include:
    - stage: test
      name: 'Test solution'
      script:
        - npm audit
        - npm test

    - stage: version
      if: branch = master and type = pull_request
      name: 'Bump new NPM version'
      script:
        - npm run version:branch $TRAVIS_PULL_REQUEST_BRANCH

    - stage: deploy
      if: branch = master and type = pull_request
      name: 'Deploy package'
      before_deploy:
        - npm run build:prod
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        cleanup: true
