language: node_js
cache:
  directories:
    - '$HOME/.npm'
install:
  - npm install

jobs:
  include:
    - stage: test
      name: 'Test solution'
      script:
        - npm audit
        - npm test

    - stage: version
      if: branch = master and type = pull_request
      name: 'Bump new NPM version'
      install: skip
      script:
        - 'which ssh-agent || ( apt-get update -qy && apt-get install openssh-client -qqy )'
        - mkdir -p ~/.ssh && eval $(ssh-agent -s) && ssh-add <(echo "$GIT_TOKEN")
        - npm run version:branch $TRAVIS_PULL_REQUEST_BRANCH

    - stage: deploy
      if: branch = master and type = pull_request
      name: 'Deploy package'
      before_deploy:
        - npm run build:prod
      deploy:
        provider: npm
        email: '$NPM_EMAIL'
        api_key: '$NPM_TOKEN'
        cleanup: true
