language: node_js
branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.npm'

before_install:
  - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
install:
  - npm install

deploy:
  script:
    - npm run publish
  skip_cleanup: true
  provider: npm
  email: ${NPM_EMAIL}
  api_key: ${NPM_TOKEN}
