language: node_js
cache:
  directories:
    - '$HOME/.npm'

jobs:
  include:
    - stage: install
      script:
        - npm install

    - stage: test
      script:
        - npm audit
        - npm run test

    - stage: version
      if: branch = master
      script:
        - npm run version:branch ${TRAVIS_PULL_REQUEST_BRANCH}

    - stage: deploy
      if: branch = master
      before_deploy:
        - npm run build:prod
      deploy:
        edge: true
        provider: npm
        email: '${NPM_EMAIL}'
        api_key: '${NPM_TOKEN}'
        cleanup: true
