language: node_js
cache:
  directories:
    - '$HOME/.npm'

jobs:
  include:
    - stage: install
      script:
        - npm install

    - stage: test
      script:
        - npm audit
        - npm run test

    - stage: version
      script:
        - npm run version:branch ${TRAVIS_PULL_REQUEST_BRANCH}

    - stage: deploy
      if: branch = master AND commit_message =~ /^[0-9]*\.[0-9]*\.[0-9]*$/
      before_deploy:
        - npm run build:prod
      deploy:
        edge: true
        provider: npm
        email: '${NPM_EMAIL}'
        api_key: '${NPM_TOKEN}'
        cleanup: true
