pr:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@1
    inputs:
      version: '10.x'
    displayName: 'Install Node.js'

  - task: npmAuthenticate@0
    inputs:
      workingFile: '$(System.DefaultWorkingDirectory)/.npmrc'
    displayName: Authenticate to NPM

  - script: |
      npm ci
    displayName: 'Install dependencies'

  - script: |
      npm test
    displayName: 'Test Project'

  - script: |
      npm run build:prod
    displayName: 'Build Project'
