trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UseNode@1
    inputs:
      version: '10.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install dependencies'

  - script: |
      npm test
    displayName: 'Test Project'

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'coverage-junit.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)/coverage'
      failTaskOnFailedTests: true
    displayName: Publish Coverage

  - script: |
      npm run build:prod
    displayName: 'Build Project'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        dist/*
        dist/**/*
        package.json
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'dots'
      publishLocation: 'Container'
    displayName: Publish Artifacts
